language: node_js
node_js:
  - "0.10"

before_script:
  - npm update -g npm
  - npm install grunt-cli
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install libc6:i386 libgcc1:i386 libstdc++6:i386
  - sudo apt-get install parallel

notifications:
  irc: "irc.mozilla.org#shumway"
